apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
- istio.yaml
- monitoring-gateway.yaml
- monitoring-virtualservices.yaml
- historical-network-gateway.yaml

configMapGenerator:
- name: istio-values
  files:
  - values.yaml